- libs/messages-provider/LICENSE
- libs/messages-provider/README.md
- libs/messages-provider/babel.config.json
- libs/messages-provider/package-lock.json
- libs/messages-provider/package.json
- libs/messages-provider/rollup.config.js
- libs/messages-provider/setupTests.js
- libs/messages-provider/src/Messages.js
- libs/messages-provider/src/Messages.test.js
- libs/messages-provider/src/index.js
- libs/messages-provider/src/useMessageStore.js
- libs/messages-provider/src/useMessageStore.test.js
- upgrade `juno-ui-components` to 2.14.1
- added `@rollup/plugin-node-resolve` version "^15.0.1"
- extended `jest` configuration with `transformIgnorePatterns` for `juno-ui-components`
- small changes en Readme
> [messages-provider] migrated from sapcc

- apps/template/package.json
- Engines introduce: "node": ">=20.0.0 <21.0.0", "npm": ">=10.0.0 <11.0.0"
- Set fix version of react-dom, react-test-renderer
- Upgrade version of zustand to 4.5.2
> feat(template-app) upgrade after migration

- apps/exampleapp/package.json
- set private to false
- Engines introduce: "node": ">=20.0.0 <21.0.0", "npm": ">=10.0.0 <11.0.0"
- Set fix version of libs: react-dom, react-test-renderer
- upgrade version of zustand to 4.5.2
> feat(exampleapp): upgrade after migration

- libs/template-lib/package.json
- Engines introduce: "node": ">=20.0.0 <21.0.0", "npm": ">=10.0.0 <11.0.0"
- Added missing lib: jest-environment-jsdom
> feat(template-lib): upgrade after migration

- libs/messages-provider/package.json
- Engines introduce: "node": ">=20.0.0 <21.0.0", "npm": ">=10.0.0 <11.0.0"
- Added missing lib: @rollup/plugin-node-resolve
- Upgrade juno-ui-components to 2.14.1
- Added transformIgnorePatterns
> feat(messages-provider): upgrade version after migration

- libs/url-state-router/package-lock.json
- libs/url-state-router/package.json
- correct repository URL
- fix some dependencies
- patch version upgrade
> fix(url-state-router): fix some dependencies, set correct repository and some typos

- libs/url-state-provider/package-lock.json
- libs/url-state-provider/package.json
- Fix repository URL
- Patch version upgrade
> fix(url-state-provider): fix repository and upgrade version

- libs/template-lib/package-lock.json
- libs/template-lib/package.json
- Fix repository URL
- Patch version upgrade
> fix(template-lib): fix repository and upgrade version

- libs/juno-ui-components/package-lock.json
- libs/juno-ui-components/package.json
- Align devDependencies and peerDependencies
- Patch version upgrade
> fix(juno-ui-components) align devDependencies and peerDependencies

- libs/utils/package-lock.json
- libs/utils/package.json
- libs/utils/src/hooks/useAppLoader.js
do not add @juno prefix for packages which start with @ in their name
> feat(utils): support new naming convention

- packages/url-state-provider/jest.config.js
- packages/url-state-provider/package-lock.json
- packages/url-state-provider/package.json
- packages/url-state-provider/src/index.js
- packages/url-state-provider/src/index.test.js
- packages/url-state-provider/src/superstate.js
- packages/url-state-provider/src/superstate.test.js
The new custom encoding and decoding with following benifits:
- URI-safe encoding with RFC 3986 compatible characters 
- Support for various data types (like numbers, regex, strings, array ())
- The encoding can handle nested objects and arrays, maintaining their structure through the encoding and decoding process
- human readable
- Encoding supports also lz-compression and base64, while maintaining structure and data types
- Special characters in strings can not crash the decoding anymore like with JURI  are encodes with ~ or % 
- spaces are now encoded with a +  
- Error handling: The code includes error checking and provides options for null returns on decoding errors
- 100% test coverage for the encoding and decoding
-  fully implement all features of the encoding in …
> feat(url-state-provider): URI-Safe, and readable encoding and compression of various data types and nested objects

- packages/url-state-router/eslint.config.mjs
- packages/url-state-router/src/Link.js
- packages/url-state-router/src/Route.js
- packages/url-state-router/src/Router.js
- packages/url-state-router/src/Router.test.js
- packages/url-state-router/src/Switch.js
- packages/url-state-router/src/routeMatcher.js
- packages/url-state-router/src/useURLStateProvider.test.js
Fix all lint issues for url-state-router
- fixed lint issues in components and tests
- adjust the eslint config in url-state-router to declare test files as modules
- Issue 1: #102 
1. `npm i --force`
2. `npm run lint -w @cloudoperators/juno-url-state-router`
> chore(eslint): fix lint issues in url-state-router

- package-lock.json
- packages/esflint-config/juno.mjs
- packages/messages-provider/eslint.config.mjs
- packages/messages-provider/rollup.config.js
- packages/messages-provider/src/Messages.js
- packages/messages-provider/src/useMessageStore.js
- packages/utils/eslint.config.mjs
- packages/utils/package.json
- packages/utils/rollup.config.js
- packages/utils/src/hooks/useAppLoader.js
- packages/utils/src/hooks/useEndlessScrollList.test.js
- packages/utils/src/lib/fetchProxy.js
- packages/utils/src/lib/fetchProxy.test.js
Fix eslint issues for messages-provider.
- adjust eslint config to ignore jest setup file
- fixed lint issues
- Issue 1: #102 
1. `npm i -f`
2. `npx turbo lint --filter=@cloudoperators/juno-messages-provider`
> Andypf eslint mesages provider

- package-lock.json
- packages/esflint-config/juno.mjs
- packages/utils/eslint.config.mjs
- packages/utils/package.json
- packages/utils/rollup.config.js
- packages/utils/src/hooks/useAppLoader.js
- packages/utils/src/hooks/useEndlessScrollList.test.js
- packages/utils/src/lib/fetchProxy.js
- packages/utils/src/lib/fetchProxy.test.js
Fix lint issues for utils.
- upgrade @testing-library/react to latest
- fix lint issues
- Issue 1: #102 
1. `npm i --force`
2. `npx turbo lint --filter=@cloudoperators/juno-utils`
> chore(eslint): fix lint issues in utils

- package-lock.json
- packages/url-state-provider/README.md
- packages/url-state-provider/eslint.config.mjs
- packages/url-state-provider/package.json
- packages/url-state-provider/src/index.js
- packages/url-state-provider/src/index.test.js
- packages/url-state-provider/src/superstate.js
- packages/url-state-provider/src/superstate.test.js
reduced code smells and documented encoding.
> chore(url-state-provider): Mitigated code smells and document encoding

- apps/example/esbuild.config.js
- apps/example/eslint.config.mjs
- apps/example/src/App.jsx
- apps/example/src/components/AppContent.js
- apps/example/src/components/AsyncWorker.jsx
- apps/example/src/components/MonorepoChecker.jsx
- apps/example/src/components/Playground.js
- apps/example/src/components/StoreProvider.jsx
- apps/example/src/components/TestModal.js
- apps/example/src/components/WelcomeView.js
- apps/example/src/components/auth/Avatar.js
- apps/example/src/components/auth/HeaderUser.js
- apps/example/src/components/peaks/PeaksEdit.js
- apps/example/src/components/peaks/PeaksList.js
- apps/example/src/components/peaks/PeaksListItem.js
- apps/example/src/components/peaks/PeaksNew.jsx
- apps/example/src/components/shared/HintLoading.js
- apps/example/src/components/shared/HintNotFound.jsx
- apps/example/src/hooks/useQueryClientFn.js
- apps/example/src/lib/store/createAuthSlice.js
- apps/example/src/lib/store/createGlobalsSlice.js
- apps/example/tailwind.config.js
- apps/template/esbuild.config.js
- apps/template/eslint.config.mjs
- apps/template/src/App.js
- apps/template/src/App.test.js
- apps/template/src/AppContent.js
- apps/template/src/components/StoreProvider.js
- apps/template/tailwind.config.js
Fix all lint issues in all apps.
- adjust eslint configs in template and example apps
- fix issues
- Issue 1: #102 
1. `npm i -f`
2. `npx turbo lint`
> chore(eslint): fix lint issues in apps

- .github/workflows/deploy-github-pages.yaml
> fix(workflow) remove cname from deploy-github-pages

- .github/pull_request_template.md
- .github/workflows/deploy-github-pages.yaml
Improve Template
- Changed template for PRs
- Renamed workflow for Storybook
> chor(workflow): change name and improve template

- .changeset/config.json
- apps/example/eslint.config.mjs
- apps/example/package.json
- apps/template/eslint.config.mjs
- apps/template/package.json
- package-lock.json
- packages/communicator/eslint.config.mjs
- packages/communicator/package.json
- packages/eslint-config/README.md
- packages/eslint-config/package.json
- packages/messages-provider/eslint.config.mjs
- packages/messages-provider/package.json
- packages/oauth/eslint.config.mjs
- packages/oauth/package.json
- packages/template/eslint.config.mjs
- packages/template/package.json
- packages/ui-components/eslint.config.mjs
- packages/ui-components/package.json
- packages/url-state-provider/eslint.config.mjs
- packages/url-state-provider/package.json
- packages/url-state-router/eslint.config.mjs
- packages/url-state-router/package.json
- packages/utils/eslint.config.mjs
- packages/utils/package.json
Change access level to pubic
- Update changeset config
- Issue 1: #102
1. `npm i`
> Andypf publish details

- .github/workflows/release.yaml
Add Permissions to the release workflow.
> chore(workflow): add permmissions to release

- .changeset/gorgeous-goats-tell.md
- packages/communicator/README.md
- packages/messages-provider/README.md
- packages/oauth/README.md
- packages/ui-components/README.md
- packages/url-state-provider/README.md
- packages/url-state-router/README.md
- packages/utils/README.md
Since we changed the name of packages adding the @cloudoperators prefix we also should update the instructions in readme files.
- Update Install Section
- Update import from
> chore(readme): update instructions in readme files

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/task.md
This is a templates for typical common tasks: 
- Bug report
- Feature request
- Task breakdown templates
- #116
> chore(templates): Feature request, task, bug report templates

- .github/workflows/release.yaml
Customize title and commit messages for Version Update PRs
- Added the title property to changeset action
- Added commit property to changeset action
> chor(release): customize title and commit message for release PR

- .changeset/rude-dots-tap.md
- packages/oauth/src/tokenHelpers.js
This pull request addresses the issue identified by CodeQL regarding the “Polynomial regular expression used on uncontrolled data” in the OAuth module. The problematic regular expression has been revised to enhance both efficiency and security.
- replace email regex with more specific regex
> Andypf security issues

- .changeset/young-chefs-decide.md
- .github/workflows/ci-checks.yaml
This pull request addresses a version mismatch issue between the published packages and the automatically tracked package versions caused by a manual publishing process. To resolve this discrepancy, the version of the OAuth package has been incremented accordingly.
- patch version of oauth
- update ci-checks workflow: run checks also on Version PR edit
> feat(oauth): bump new version

- packages/communicator/CHANGELOG.md
- packages/communicator/package.json
- packages/messages-provider/CHANGELOG.md
- packages/messages-provider/package.json
- packages/oauth/CHANGELOG.md
- packages/oauth/package.json
- packages/ui-components/CHANGELOG.md
- packages/ui-components/package.json
- packages/url-state-provider/CHANGELOG.md
- packages/url-state-provider/package.json
- packages/url-state-router/CHANGELOG.md
- packages/url-state-router/package.json
- packages/utils/CHANGELOG.md
- packages/utils/package.json
Update versions and change logs due to the changes in readme files.
- update change log using changeset cli
- update package versions using changeset version cli
> chore(readme): update package versions

- .changeset/fuzzy-tables-lie.md
- .changeset/great-boats-eat.md
This PR updates the versions for ui-components and oauth
- update changeset for ui-components
- update changeset for oauth
> chore(versions): fix changelog for oauth and ui-components

- .github/workflows/deploy-pr-preview.yaml
> fix(workflow) deactivate paths-ignore because of error only define one of `paths` and `paths-ignore` for a single event

- packages/ui-components/.storybook/juno-addon/themes.js
- Change link from storybook Juno UI logo to itself
- Display the actual version of the package in the logo section
> feat(storybook): point storybook Juno UI logo link to itself and add version

- .github/workflows/ci-title-lint-check.yaml
- .github/workflows/release.yaml
- package-lock.json
- packages/communicator/package.json
- packages/k8s-client/package.json
- packages/k8s-client/src/apiErrorHandler.ts
Super simple PR that fix vulnerability of axios dependency.
- Fix axios deps types
- Fix module in communicator
1. `npm i`
2. `npm run test, build, or typecheck`
> chore(k8s): delete axios dependency  and update workflow

- .changeset/sweet-cameras-develop.md
- packages/communicator/package.json
- packages/communicator/vite.config.mts
Change build output to make asset server works.
- build change to index.js
1. `npm i`
> fix(communicator): change build output of communicator

- .github/workflows/release.yaml
Ignore husky for release
- Change 1
- Change 2
- Change 3
1. `npm i`
> chore(infra): ignore husky

- packages/ui-components/src/components/CheckboxGroup/CheckboxGroup.component.js
- packages/ui-components/src/components/FormHint/FormHint.component.js
- packages/ui-components/src/components/FormHintTs/FormHint.component.tsx
- packages/ui-components/src/components/FormHintTs/FormHint.stories.tsx
- packages/ui-components/src/components/FormHintTs/FormHint.test.tsx
- packages/ui-components/src/components/FormHintTs/index.ts
- packages/ui-components/src/components/Label/Label.stories.js
- packages/ui-components/src/components/LabelTs/Label.component.tsx
- packages/ui-components/src/components/LabelTs/Label.stories.ts
- packages/ui-components/src/components/LabelTs/Label.test.tsx
- packages/ui-components/src/components/LabelTs/index.ts
- packages/ui-components/src/components/SecretText/SecretText.component.js
- packages/ui-components/src/components/TextAreaTs/Textarea.component.tsx
- packages/ui-components/src/components/TextAreaTs/Textarea.stories.tsx
- packages/ui-components/src/components/TextAreaTs/Textarea.test.tsx
- packages/ui-components/src/components/TextAreaTs/index.ts
- packages/ui-components/src/components/Textarea/Textarea.stories.js
Introduce TS version of TextBox and dependencies
Migrated to TS TextBox, Label and FormHint as new components to replace their JS versions
- Issue 1: [https://github.com/cloudoperators/juno/issues/257]
1. `npm i`
2. `npm run test`
> chore(ui): introduce TS version of TextBox and dependencies

- docs/getting-started.md
- package.json
Add a dedicated script to start a specific application to avoid to start all aplications at once when running the dev command
- Add new command to the root package.json
- Added description to the reame
1. `npm i`
> chore(infra): add a dedicated script to start a specific application

- .github/workflows/check-licenses-npm-package.yaml
Fix the license dependency checker by specifying a fixed version to avoid issues with the broken latest release.
- Fix workflow check-licenses-npm-package
1. `npm i`
> chore(infra): fix license dependency checker

- .github/workflows/ci-checks.yaml
- .github/workflows/ci-title-lint-check.yaml
This PR is changing 2 actions to use load them from [common](https://github.com/cloudoperators/common) as shared `GitHub Action`
- reuse action
- license header action changed
- Change 3
> feat(build): use shared actions from common

- .dockerignore
- apps/supernova/docker/Dockerfile
- apps/supernova/docker/README.md
Fixes docker image building supernova with turbo
- Run docker file from root with turbo
- Apdapted readme
1. `npm i`
> fix(ci): fixes docker image building supernova with turbo

- .github/workflows/build-push-supernova-image.yaml
Fixes context when building supernova image from the workflow.
- Changed context in the workflow
- Change 2
- Change 3
1. `npm i`
> fix(ci): fixes context when building supernova image from the workflow

- apps/doop/eslint.config.mjs
- apps/doop/helpers/appProps.js
- apps/doop/src/App.test.js
- apps/doop/src/components/AppContent.jsx
- apps/doop/src/components/Header.jsx
- apps/doop/src/components/Highlighter.jsx
- apps/doop/src/components/filters/FilterSelect.jsx
- apps/doop/src/components/violations/ViolationDetails.jsx
- apps/doop/src/components/violations/ViolationDetailsList.jsx
- apps/doop/src/components/violations/ViolationDetailsOccurrences.jsx
- apps/doop/src/components/violations/ViolationDetailsPills.jsx
- apps/doop/src/components/violations/ViolationSeverity.jsx
- apps/doop/src/components/violations/ViolationsListItem.jsx
- apps/doop/src/lib/apiClient.js
- apps/doop/src/lib/helpers.js
- apps/doop/src/lib/store/createGlobalsSlice.js
- apps/doop/src/lib/store/createUserActivitySlice.js
- apps/doop/tailwind.config.js
> chore(doop): reduced linting errors

- apps/supernova/docker/Dockerfile
Adds labels to the docker image to be displayed in ghcr as description.
- Adds labels to the docker image
1. `npm i`
> chore(ci): adds labels to the docker image to be displayed in ghcr

- .husky/pre-commit
- .husky/pre-push
- package.json
- turbo.json
This PR enhances the configuration of Husky and Turborepo.
- Removed persistent settings from turbo.json, allowing for reduced concurrency and better CPU load management.
- Removed the test task from the pre-push GitHub hook to streamline the push workflow.
1. `npm i`
> chore(ci): do not run tests on push

- .changeset/tame-rivers-dress.md
- apps/supernova/README.md
To give people an idea what the Supernova UI looks like, add some screenshots.
Also add a getting started section, referring to the published image and its documentation, as well as how to start Supernova in dev mode.
- Screenshots added to README
- Getting Started section added (describes docker image and dev mode)
> chore(supernova): add screenshots and getting started to readme

- .github/workflows/build-push-greenhouse-image.yaml
- .github/workflows/ci-title-lint-check.yaml
- apps/greenhouse/apps/types/package.json
- apps/greenhouse/apps/utils/package.json
This PR adds the version attribute to package.json files.
- add version to apps/greenhouse/apps/types
- add version to apps/greenhouse/apps/utils
> chore(greenhouse): add version to packageJson files

- .changeset/little-onions-obey.md
This PR removes the fake changeset and unblocks the Release workflow 👍
> chore(ci): remove fake changeset from .changeset

- .github/workflows/build-push-greenhouse-image.yaml
optimizes the image build for greenhouse dashboard
> chore(greenhouse): optimize image build with trivy check

- .github/workflows/build-push-supernova-image.yaml
- .github/workflows/ci-checks.yaml
repair testing and add some nice icons
> chore(ci): repair checks and add icons

- packages/ui-components/src/components/SideNavigation/SideNavigation.test.tsx
- packages/ui-components/src/components/SideNavigationItem/SideNavigationItem.test.tsx
- packages/ui-components/src/components/TabNavigation/TabNavigation.test.tsx
- packages/ui-components/src/components/TabNavigationItem/TabNavigationItem.test.tsx
- packages/ui-components/src/components/Toast/Toast.test.tsx
- packages/ui-components/src/components/Tooltip/Tooltip.test.tsx
- packages/ui-components/src/components/TopNavigation/TopNavigation.test.tsx
Stabilized all tests by addressing potential race conditions. Implemented `waitFor` and `act` where necessary to ensure proper timing and synchronization across asynchronous operations.
Act update unfrotently brought problems for tests that was exectued with vitest. I suggest that we need to fix all warnings that came with this update.
- Wrapped component tests with act
- waitFor
- Fix linting
1. `npm i`
> chore(ui): stabilize ui components tests everywhere

- packages/utils/README.md
Renamed all occurrences of `@cloudoperators/utils` to `@cloudoperators/juno-utils` and updated all references to use "Juno Utils in the readme file
- Readme 
1. `npm i`
> chore(utils): renamed to @cloudoperators/juno-utils and updated all references to Juno Utils

- docs/proposals/001_modulith_architecture.md
This PR adds a proposal document outlining the Modulith Dashboard Architecture (Code Name: `Carbon`) under docs/proposals. The document details the new architecture’s design, which combines the stability of a monolithic core with the flexibility of a modular system. It serves as a foundational reference for future development and planning.
> feat(docs): adds a proposal for modulith arch

- apps/example/README.md
- apps/example/appProps.template.js
- apps/example/vite.config.ts
This PR renames the build folder from dist to build and adds a appProps.template.js file with instructions. Also it adds a correspondent note to the README
> chore(example): improve build and docs 

- .github/workflows/build-push-greenhouse-image.yaml
- apps/greenhouse/docker/Dockerfile
- apps/greenhouse/docker/index.html
This PR makes the check für Image existence conditional by adding if statement. 
1. Check for Image Existence:
Added a conditional check to verify if the Docker image exists before attempting to push it. This prevents unnecessary steps in the pipeline and avoids potential errors when the image is missing.
2. Update Greenhouse Import:
Updated the index.js file to use the current version of the Greenhouse app in the import statement. This ensures that the latest features and fixes from Greenhouse are correctly integrated.
> fix(ci): adds Conditional Check for Image Existence

- docs/proposals/002_greenhouse_deployment.md
This pull request introduces a document in the docs/proposals directory that outlines the current challenges we face with the deployment of Greenhouse and presents some initial ideas for improvement. The purpose of this PR is to invite collaboration by encouraging team members to contribute additional ideas or make edits to the existing content.
> chore(docs): adds a initial proposal for gh deployment

- apps/example/turbo.json
This PR adds needed packages to turbo.json in apps/example to resolve dependent packages while build and build:static.
> chore(example): add needed packages to turbo deps

- apps/greenhouse/src/components/core-apps/org-admin/components/teams/components/StoreProvider.test.jsx
- apps/greenhouse/vitest.setup.ts
- package-lock.json
This PR updates the dependencies in package-lock.json and includes adjustments to the greenhouse tests, ensuring all tests pass successfully.
1. `npm i`
> chore(ci): update deps to fix tests

- .github/renovate.json
As all npm dependencies of `ui-components` package were manually upgraded to the latest `patch` version recently. This PR tries to automate this process using renovate.
- Removed stale configurations
- Added new configurations for only for `ui-components` package.
- https://github.com/cloudoperators/juno/issues/637
We need to first merge these configurations and then see if renovates creates PRs for patch versions.
> chore(ui): enable renovate for patch versions

- .changeset/selfish-icons-divide.md
- apps/heureka/src/lib/queries/services.js
This PR includes only a small change in services query. 
The `metadata` section is changed to `objectMetadata`.
> chore(heureka): updates services query based on minor API related changes

- .changeset/beige-chicken-begin.md
- apps/carbon/package.json
- package-lock.json
- package.json
- packages/ui-components/src/hooks/useEndlessScrollList.tsx
Deleted npm-run-all and used npm audit fix 
1. `npm i`
> chore(core): update dependencies to fix vulnerability

- .changeset/empty-dolls-dream.md
- apps/heureka/src/lib/queries/services.js
This PR updates the service details query based on recent API changes. 
`metadata` is changes to `objectMetadata`.
> chore(heureka): updates service details query

- .changeset/twenty-books-visit.md
- packages/ui-components/src/components/Modal/Modal.stories.tsx
reintroduce portal-based Modal stories
- reintroduce portal-based Modal stories
- Issue 1: [https://github.com/cloudoperators/juno/issues/520]
1. `npm i`
2. `npm run storybook`
> fix(ui): reintroduce portal-based Modal stories

- .changeset/kind-maps-shout.md
- packages/ui-components/src/components/DateTimePicker/DateTimePicker.component.tsx
- packages/ui-components/src/components/DateTimePicker/DateTimePicker.test.tsx
Fix DateTimePicker runtime errors
- Fix DateTimePicker runtime errors
- Issue 1: [[link to issue](https://github.com/cloudoperators/juno/issues/695)]
1. `npm i`
2. `npm run storybook`
> fix(ui): fix DateTimePicker runtime errors

- .changeset/silent-mails-juggle.md
- packages/oauth/src/tokenSession.ts
This PR addresses the improvements proposed in [PR #708](https://github.com/cloudoperators/juno/pull/708) by implementing enhanced TypeScript types and incorporating feedback received during the review process.
- Enhanced TypeScript types for improved type safety and maintainability.
- Fixes #714
1. `npm run clean`
2. `npn run clean:cache`
3. `npm i`
4. `npx turbo test --filter @cloudoperators/juno-oauth`
> chore(oauth): applies proposed type improvements

- .changeset/polite-hairs-nail.md
This PR synchronizes Greenhouse with the latest versions of the Juno applications (extensions) and libraries.
- Added a changeset
1. `npm i`
> chore(greenhouse): adds a changeset to greenhouse to synch with dependent libs and apps

- .changeset/witty-buttons-compete.md
- packages/ui-components/src/components/Icon/Icon.component.tsx
- Add changeset for https://github.com/cloudoperators/juno/pull/726/files
- Fix `Icon` display name
> chore(ui): add changeset for vite configuration fix to enable types in juno-ui-components

- .github/pull_request_template.md
This change proposes an addition to the checklist in the PR template.
- Added "I have created a changeset" to the checklist
> chore(config): add changeset creation to PR checklist

- .changeset/orange-spoons-flash.md
- package.json
Adds `npm install` during the release action to ensure dependencies are updated correctly when creating changesets that affect other apps or libraries.
- Adds `npm i` in the release command used in the release action
1. `npm i`
> chore(ci): adds npm install when releasing

- .changeset/lazy-bugs-cross.md
Adds changeset to greenhouse.
- Adds a changeset to greenhouse
> chore(greenhouse): adds changeset to greenhouse

- .changeset/orange-spoons-flash.md
Removes test changeset
- Removes files
> chore(ui): remove changeset

- .changeset/stale-months-cheer.md
- apps/heureka/index.html
- apps/heureka/src/index.tsx
Ensures app mounts correctly with props object in standalone and embedded mode.
- `index.html` now passes a single object containing all props.  
- `index.ts` extracts and passes the props to the application.  
1. `npm i`
2. `npx turbo dev --filter @cloudoperators/juno-app-greenhouse`
3. Check the app runs
> fix(heureka): ensures app mounts correctly with props object

- .changeset/polite-falcons-perform.md
Adds changeset to integrate new version of heureka into greenhouse
- Added changeset
> chore(greenhouse): adds changeset to integrate new version of heureka into greenhouse

- .changeset/tricky-carrots-appear.md
- apps/carbon/package.json
- apps/doop/package.json
- apps/example/package.json
- apps/greenhouse/package.json
- apps/heureka/package.json
- apps/template/package.json
- package-lock.json
- packages/communicator/package.json
- packages/k8s-client/package.json
- packages/messages-provider/package.json
- packages/oauth/package.json
- packages/template/package.json
- packages/ui-components/package.json
- packages/url-state-provider/package.json
- Update vite version to 6.0
- [Task: upgrade to vite 6.0 ](https://github.com/cloudoperators/juno/issues/848)
1. `npm i`
> chore(juno): update vite version to 6.0

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/epic.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/task.md
Github has introduced issue types recently. Having issue types is a nice improvement over our previous solution of using a custom field for issue types because this will now allow us to specify the matching issue type in our issue templates so that issues created with a template automatically set the correct `type` for the issue.
- Introduced new epic issue type
- Updated our project to use the `type` property rather than our old issue type custom field for filtering and sorting
- Updated all epics and all open issues with their correct type
- Updated issue templates to automatically set the correct type (this PR)
> chore(config): update issue templates and add new type property

- .changeset/smooth-lobsters-play.md
- apps/carbon/package.json
- apps/doop/package.json
- apps/example/package.json
- apps/greenhouse/package.json
- apps/heureka/package.json
- apps/template/package.json
- package-lock.json
- packages/communicator/package.json
- packages/k8s-client/package.json
- packages/messages-provider/package.json
- packages/oauth/package.json
- packages/template/package.json
- packages/ui-components/package.json
- packages/url-state-provider/package.json
- Upgrade Vite to version 6 to leverage new features, performance improvements, and bug fixes. Ensure compatibility with the existing setup and resolve any breaking changes.
- https://github.com/cloudoperators/juno/issues/848
1. `npm i`
> chore(deps): upgrade to vite 6.2

- .changeset/eighty-gifts-juggle.md
- apps/heureka/src/components/Services/useFetchServicesCounts.ts
- apps/heureka/src/generated/graphql.ts
IssueCounts filtering has been enhanced to include a new option for filtering by ServiceOwner ID and name.
- IssueCounts component extended with filtering by ServiceOwner ID and name.
- https://github.com/cloudoperators/heureka/pull/567
1. `npm i`
2. `npx turbo dev --filter @cloudoperators/juno-app-heureka`
> feat(heureka): applies new user filters to issueCounts

- .changeset/rich-flowers-obey.md
This pull request introduces a changeset to prepare for a **major release** of the `@cloudoperators/juno-ui-components` package. It includes breaking changes and improvements aligned with our design and component standards.
- Major release 
- Issue 1: https://github.com/cloudoperators/juno/issues/1234
1. `npm i`
2. `npm run changeset`
> chore(ui): changeset for major version release

- .changeset/silver-peaches-complain.md
- apps/heureka/src/components/ServiceDetails/ImageVersionDetailsPanel/ImageVersionIssuesList/ImageVersionIssueListItem/index.tsx
This PR improves the text truncation behavior in the issue descriptions list by replacing the manual substring truncation with CSS-based text ellipsis. This change makes the text truncation more consistent with the rest of the application's UI patterns and provides a better user experience.
- Replaced manual substring truncation (substring(0, 95)) with CSS-based text truncation in ImageVersionIssueListItem
- Added CSS classes (whitespace-nowrap, overflow-hidden, text-ellipsis) for consistent text truncation
- Improved responsiveness to different screen sizes by letting the container determine the truncation point
- Prevented cutting words in the middle by using CSS ellipsis instead of character count
- Aligned the text truncation behavior with the application's existing UI patterns (like …
> chore(heureka): improves issue description truncation in ImageVersionIssueListItem

- .github/workflows/ci-checks.yaml
Improve the ci-checks workflow by using commit SHAs for enhanced security. Fixes the cache in test step and increase consistency by leveraging a matrix strategy instead of repeating identical steps across multiple jobs.
- Switched from using Git tags to commit SHAs  for enhanced security.
- Fixes the cache in test step.
- Uses a matrix to eliminate duplication.
- #834
> chore(ci): rework ci-checks workflow and use SHAs and fix duplication issues by using matrix

- .github/renovate.json
This PR introduces a scoped Renovate configuration to enable automated dependency updates for `apps/heureka`.
- Renovate configuration extended
- #971
> chore(ci): enable Renovate for heureka with scoped config

- .changeset/chubby-sheep-fry.md
- packages/ui-components/src/components/Grid/Grid.stories.tsx
- packages/ui-components/src/components/GridColumn/GridColumn.stories.tsx
- packages/ui-components/src/components/Icon/Icon.stories.ts
- packages/ui-components/src/components/LoadingIndicator/LoadingIndicator.stories.tsx
- packages/ui-components/src/components/Modal/Modal.stories.tsx
- packages/ui-components/src/components/ModalFooter/ModalFooter.stories.tsx
- packages/ui-components/src/components/Panel/Panel.stories.tsx
- packages/ui-components/src/components/PanelBody/PanelBody.stories.tsx
- packages/ui-components/src/components/PanelFooter/PanelFooter.stories.tsx
- packages/ui-components/src/components/Stack/Stack.stories.tsx
Issue: https://github.com/cloudoperators/juno/issues/1016
- Removed all "jn:" prefixes from visible Storybook documentation as they're meant for internal ui-components use only.
- Removed visible `PortalProvider` from `Modal` story. <img width="632" height="751" alt="Screenshot 2025-07-18 at 09 51 44" src="https://github.com/user-attachments/assets/0b7f2544-4e3e-4dd0-b079-aa195ebf6e26" />
- Removed `undefined` `className` from `GridColumns` story. <img width="799" height="362" alt="Screenshot 2025-07-17 at 22 25 59" src="https://github.com/user-attachments/assets/8b9b3a57-05ac-45ed-8d2a-b24ea7f908d8" />
- Raised new issue https://github.com/cloudoperators/juno/issues/1087 for improving default values in controls.
- Fulfilled all ACs.
Review the [PR …
> chore(docs): enhance storybook code examples 

- apps/heureka/src/components/common/Filters/index.test.tsx
Skip test that randomly timeout.
- Skip test
1. `pnpm i`
2. `pnpm TASK`
> test(heureka): skip test that randomly times out

- .changeset/huge-worlds-tell.md
- packages/ui-components/src/components/Modal/Modal.component.tsx
- packages/ui-components/src/components/Modal/Modal.stories.tsx
Issue: https://github.com/cloudoperators/juno/issues/1120
- Added `xl` and `2xl` sizes to `Modal`.
- Fulfilled all ACs.
Reviewers: **Please** see `Quality Assurance` section in the main ticket. 🙏
> feat(ui): add new sizes to Modal

- .changeset/shy-snails-follow.md
This PR adds changeset for kubernetes client.
1. `pnpm i`
2. `pnpm TASK`
> chore(kubernetes): add changeset for k8s
