cloudoperators/juno

- libs/url-state-router/package.json
Engines introduce: "node": ">=20.0.0 <21.0.0", "npm": ">=10.0.0 <11.0.0"
Upgrade @rollup/plugin-node-resolve to ^15.1.3
Added missing lib: @rollup/plugin-commonjs
Fixed version for react-dom
> feat(url-state-router): upgrade after migration

- libs/url-state-provider/package.json
Engines introduce: "node": ">=20.0.0 <21.0.0", "npm": ">=10.0.0 <11.0.0"
Added missing libs: @rollup/plugin-commonjs": "^24.0.0, @rollup/plugin-node-resolve, @rollup/plugin-terser
> feat(url-state-provider): upgrade after migration

- docs/decision_naming_schema.md
Enhanced the naming schema documentation to provide a clearer explanation and examples for directories and `package.json` entries within our project. This update ensures consistency and understanding of how packages and directories are named and organized across our codebase.
- Added detailed components of the naming schema.
- Included examples illustrating usage in different contexts.
- Clarified the role of `@<OWNER>` and its usage in `package.json` for namespace organization.
This commit aims to improve documentation clarity and maintainability for developers working with our project's directory and package naming conventions.
> docs(naming): Define  naming schema for directories and `package.json`

- libs/juno-ui-components/.storybook/main.js
- libs/juno-ui-components/public/built-with-juno.svg
- Host in github pages own 'built with juno' badge
- Fix GitHub's markdown renderer does not support embedded images using base64 encoded data URIs
> feat(juno-ui-components) host badge 'built with juno'

- .github/CODEOWNERS
Change CODEOWNERS entries such that we use the frontend team as much as possible rather than individual contributors to make future maintenance easier.
- replace individual contributors with team
- Issue 1: #38
> fix: use team instead of individual contributors for CODEOWNERS

- .github/workflows/release.yaml
When you use the repository’s GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository’s GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur. This is why we need another token to create release pull requests
- Use custom token to create a release pull request
1. `npm i`
> fix(ci): custom token to create release pull request

- .github/workflows/release.yaml
This PR updates the key in the release workflow from CHANGESET_GITHUB_TOKEN to GITHUB_TOKEN. We had previously used CHANGESET_GITHUB_TOKEN, a personal access token (PAT), in an attempt to make the checks work for release PRs. Unfortunately, this approach was unsuccessful, so we are reverting back to GITHUB_TOKEN to ensure that the author of automated release PRs is correctly set to the GitHub bot again.
> chore(ci): switch back to GITHUB_TOKEN

- .github/workflows/release.yaml
This PR addresses an issue with sending Slack notifications where JSON content was not being posted correctly. The notification failed due to improper integration of JSON content as a substring in the value of the payload.
- Fixes Posting Slack Messages with JSON Content
- Resolved Slack Notification Failure
1. `npm i`
> fix(ci): fixes posting slack messages with JSON content from the step before

- .changeset/green-paws-warn.md
- apps/supernova/src/components/silences/RecreateSilence.jsx
- apps/supernova/src/components/silences/SilenceNew.jsx
- apps/supernova/src/components/silences/SilenceScheduled.jsx
- apps/supernova/src/lib/createAuthDataSlice.js
Bind disabled TextInput directly to authName to ensure correctness. To ensure the field is disabled if there is a name.
> fix(supernova): bind disabled TextInput directly to authName

- .changeset/gentle-rabbits-add.md
- apps/supernova/public/index.html
- apps/supernova/src/hooks/useCommunication.js
- apps/supernova/src/lib/createAuthDataSlice.js
Fixes an issue where the support group filter was re-added when the active filters were cleared. The logic has been temporarily moved to the store to prevent unnecessary re-renders.
- Added a new method to the Auth slice (to be removed once initial filter setup is implemented)
- Refactored the `useCommunication` hook for better performance and clarity.
1. `npm i`
> fix(supernova): fixes the issue where the support group filter was re-added when the active filters became empty

- .changeset/two-carrots-mate.md
- apps/heureka/src/components/filters/FilterSelect.jsx
- apps/heureka/src/components/filters/Filters.jsx
- apps/heureka/src/components/issueMatches/IssueMatchesView.jsx
- apps/heureka/src/components/services/ServicesView.jsx
Customized the search input placeholder for the following views:
- IssueMatches view: Placeholder now displays "search term for primary name."
- Services view: Placeholder now displays "search term for service name."
This change provides clearer context for users based on the specific field being searched in each view.
- https://github.com/cloudoperators/heureka/issues/302
1. `npm i`
> feat(heureka): customizes search placeholder based on different views

- .changeset/sweet-items-rescue.md
- apps/heureka/src/components/filters/FilterSelect.jsx
- apps/heureka/src/components/filters/Filters.jsx
- apps/heureka/src/lib/slices/createFiltersSlice.js
- apps/heureka/src/lib/slices/createFiltersSlice.test.js
This PR updates the filter label display logic to utilize the displayName returned from the API when retrieving filter information. This ensures consistency in filter labels across different views.
- Integrated displayName into the labels of initialFilters for each entity in the filter slice.
- Modified the Filter and FilterSelect components to use displayName as labels and filterName as values, enhancing the filter prop construction in the fetch query.
- Updated the filter slice tests to reflect these changes.
- https://github.com/cloudoperators/heureka/issues/306
1. `npm i`
> chore(heureka): harmonizes filter names in different viewes

- .changeset/tiny-cooks-try.md
- packages/ui-components/src/components/Label/Label.component.tsx
- packages/ui-components/src/components/PageHeader/PageHeader.component.tsx
- packages/ui-components/src/components/PortalProvider/PortalProvider.component.tsx
- packages/ui-components/src/deprecated_js/PortalProvider/PortalProvider.component.js
This PR tries to improve upon the previous fix for the z-index stacking problem introduced in the recent refactoring of `PortalProvider`. While the previous fix in https://github.com/cloudoperators/juno/pull/565 solved the issue for Juno apps we still had potential z-index stacking issues if a Juno app was embedded into a host app with its own z-index stack. This is because the solution from the previous PR aimed to standardize all z-index on the root level to `1` and then added stacks above this in the portaled components as necessary. 
In the cases where a Juno app is embedded in a host app with z-indexes higher than `1` the whole thing would break.
This PR aims to fix this by setting a very high z-index (`9999`) for the portal root div which acts as the wrapper for all portals. So as …
> fix(ui): adds high z-index to portal root

- packages/ui-components/src/components/Grid/Grid.stories.tsx
- packages/ui-components/src/components/GridColumn/GridColumn.stories.tsx
- packages/ui-components/src/components/GridRow/GridRow.stories.tsx
After merging the `Grid`, `GridColumn` and `GridRow` migration [PR](https://github.com/cloudoperators/juno/pull/595), I found that Storybook had a few unintended styling changes (as below). This PR fixes these documentation changes.
**Issues Found**: Old Storybook on left, after migration on right:
Fixed Storybook, as was.
- https://github.com/cloudoperators/juno/issues/229
- Check `Grid`, `GridColumn` and `GridRow` Storybook
> chore(ui): fix Grid stories after Typescript migration

- .changeset/curly-owls-rush.md
- apps/greenhouse/src/hooks/useApi.js
This PR improves the handling of the support_group key within initialFilters in appProps. Now, support_group is added only when authData.parsed.supportGroups exists and is a valid array. If supportGroups is undefined, null, or not an array, support_group will be omitted from initialFilters, ensuring cleaner and more reliable data handling. Fixes the issue that prevented colleagues without a supportGroups value from accessing Supernova and Doop.
Related task #611
- Added a conditional spread operator to include support_group only if supportGroups is an array.
- If supportGroups does not exist or is not an array, support_group is excluded from initialFilters.
Error when no support group is set to the logged user:
1. `npm i`
2. Remove from the Auth Object the supportGroup `delete …
> fix(greenhouse): add support_group only if supportGroups exists and is an array

- .github/workflows/ci-checks.yaml
- package.json
This PR enhances the CI process by excluding markdown files from format checks. A new task, check-format-no-md, has been added to package.json to handle format checking without including markdown files.
- #453 
1. `npm i`
> chore(ci): do not check markdown files in ci

- .changeset/clean-plums-notice.md
- .changeset/plenty-windows-check.md
- apps/supernova/src/components/filters/FilterPills.jsx
- apps/supernova/src/components/filters/PredefinedFilters.jsx
- apps/supernova/src/lib/createFiltersSlice.jsx
- apps/supernova/src/lib/createFiltersSlice.test.jsx
Fix issue where activeFilters are not rendered if the value is not an array. Closes #609
1. `npm i`
- [] I have added tests that prove my fix is effective or that my feature works.
- [] I have made corresponding changes to the documentation (if applicable).
> fix(supernova): activeFilters are not rendered if value is not an array

- .github/scripts/build-vite-app.sh
- apps/carbon/vite.config.ts
- apps/doop/vite.config.ts
- apps/example/vite.config.ts
- apps/greenhouse/vite.config.ts
- apps/heureka/vite.config.ts
- apps/supernova/vite.config.ts
- package-lock.json
- package.json
This PR removes the base option from vite.config.js in all apps to prevent building relative paths for assets in production. To maintain support for previews deployed under a specific path, the base option is now configured directly in the preview workflow.
- remove `base` option from all vite configs 
- add `base`option to build-asset.sh 
1. `npm i`
> chore(ci): do not use relative asset paths in prod builds

- .github/renovate.json
Renovate was still scanning dependencies of all packages and apps. This PRs limits managers to just `npm` and `github-actions` as well as only scans dependencies for `ui-components` using `includePaths`.
- Limited managers to `npm` and `github-actions`
- Changed scan schedule
- Extended recommended config `config:best-practices`
- Removed customManager as it was just copied over from greenhouse project and not needed at the moment
- https://github.com/cloudoperators/juno/issues/637
> chore(ui): update renovate config

- apps/template/src/App.tsx
- packages/ui-components/src/components/AppShell/AppShell.component.tsx
- packages/ui-components/src/components/AppShell/AppShell.test.tsx
- packages/ui-components/src/components/HeaderContainer/HeaderContainer.component.tsx
This PR ensures that the default fullWidth behaviour is the same for both the main container and the header container.
Default behaviour is meant to be as follows:
* In non-embedded mode, fullWidthContent should default to false, unless explicitly set to true.
* In embedded mode though, fullWidthContent should default to true, unless explicitly passed as false.
If using `AppShell` for layout the main container (which holds the app content) followed this logic. However the recently added `HeaderContainer` did not, it always defaulted to `false`. This PR ensures that they both behave in the same way when it comes to defaults for this prop.
- Ensured fullWidth default is applied to both `HeaderContainer` and main container in `AppShell`
- Refactored `AppShell`: moved `HeaderContainer` to jsx …
> fix(ui): ensure main and header container default for fullwidth behaviour is the same

- .changeset/wicked-lies-cover.md
- package-lock.json
- packages/url-state-provider/package.json
- packages/url-state-provider/src/index.ts
- packages/url-state-provider/src/v2/index.ts
- packages/url-state-provider/src/v2/utils.spec.ts
- packages/url-state-provider/src/v2/utils.ts
`url-state-provider` now exports new utilities to save and read application state to the url. 
_Note:_
_These changes have been locally tested together with the `supernova` app for which the changes will follow after merging this PR._
- exported `saveStateToUrl` that takes the application state, encodes it and saves it to the URL.
- exported `readStateFromUrl` that reads and decodes state saved in the URL.
- #732 
1. `npm i`
2. `npm run test`
> feat(url-state-provider): export utilities to read/write state to the URL

- .changeset/purple-feet-swim.md
- apps/supernova/package.json
- apps/supernova/src/App.jsx
- apps/supernova/src/components/StoreProvider.jsx
- apps/supernova/src/hooks/useUrlQueryState/index.ts
- apps/supernova/src/hooks/useUrlQueryState/utils.ts
- apps/supernova/turbo.json
- package-lock.json
This PR integrates new way of saving and restoring app state from URL behind a feature flag. The idea was to develop an MVP in one app `supernova` with minimum possible changes so we could play around with it, that's why the new URL forcefully enabled but will be removed before merge.
- Integrated `saveStateToUrl` and `readStateFromUrl` to use new URL structure.
- New URL structure is behind a feature flag.
- Forcefully enabled new feature. [**SHOULD BE REMOVED BEFORE MERGE**]
- #717 
1. Go to PR preview
2. See the new URL structure
3. Add/Remove filters etc
> feat(supernova): integrate new url structure behind a feature flag

- .changeset/four-kings-lay.md
- package-lock.json
- packages/communicator/vite.config.ts
- packages/k8s-client/vite.config.ts
- packages/messages-provider/vite.config.ts
- packages/oauth/vite.config.ts
- packages/template/vite.config.ts
- packages/url-state-provider/vite.config.ts
We recently fixed issue in `ui-components` package where the types emitted to the wrong directory. I found the same issue when using `message-provider` package in new Hueraka and therefore fixing it for all remaining packages.
**Problem:**
This was an unintentional misconfiguration due to which the type definition file `index.d.ts` was being output in `build/types` where as it should co-locate with `index.js` inside `build` so the types can be recognized.
- output types to `build` rather than `build/types`
> fix(build): output types to correct directory

- .changeset/tall-pans-divide.md
- apps/greenhouse/src/components/Extensions.tsx
Fix greenhouse error, simple leftover after TS migration
1. `npm i`
http://localhost:8000/?org=ccloud&__s=(doop:(f:((id:support~Sgroup,key:check~Isupport~Sgroup,label:support_group,type:check,value:containers)),s:-+,v:-+),doop~Fkubernikus:(f:((id:support~Sgroup,key:check~Isupport~Sgroup,label:support_group,type:check,value:containers)),s:-+,v:-+),greenhouse~Fdashboard:(a:org~Fadmin),greenhouse~Forg~Fadmin:(a:%27%27),heureka:(d:-+,f:(Components:(:),IssueMatches:(:),Services:(:)),s:eyJJc3N1ZU1hdGNoZXMiOiIiLCJTZXJ2aWNlcyI6IiIsIkNvbXBvbmVudHMiOiIifQ~L~L,v:Services))
> fix(greenhouse): fix greenhouse error

- apps/carbon/package.json
- apps/doop/package.json
- apps/example/package.json
- apps/greenhouse/package.json
- apps/heureka-next/package.json
- apps/heureka/package.json
- apps/supernova/package.json
- apps/template/package.json
- package-lock.json
- packages/communicator/package.json
- packages/messages-provider/package.json
- packages/oauth/package.json
- packages/template/package.json
- packages/ui-components/package.json
- packages/url-state-provider/package.json
- packages/url-state-provider/vitest.config.ts
This PR upgrades vitest and @vitest/ui to version 3.0.7, resolving the reported vulnerability alerts.
- upgrade vitest to 3.0.7
- upgrade @vitest/ui to 3.0.7
1. `npm i`
> chore(core): upgrade vitest to 3.0.7

- .changeset/wise-guests-shop.md
- apps/heureka/README.md
- apps/heureka/src/components/Services/Services.test.tsx
- apps/heureka/src/components/Services/ServicesList/ServicesList.test.tsx
- apps/heureka/src/components/Services/ServicesList/ServicesList.tsx
- apps/heureka/src/components/Services/useFetchServices.ts
- apps/heureka/src/components/Services/utils.ts
- apps/heureka/src/components/common/Filters/Filters.tsx
- apps/heureka/src/generated/graphql.ts
- apps/heureka/src/graphql/Services/getServices.graphql
- apps/heureka/src/mocks/fixtures/services.json
This PR mainly fixes pagination issue that happened due to a change in the backend. Additionally services are now sorted by name.
- Fix pagination
- Sort services by name
- Aligns pagination controls to the right
- Fixes `Clear All` button by leaving some space on the left
- #818 
> fix(heureka): fix pagination

- .changeset/chilled-fireants-joke.md
- apps/heureka/README.md
- apps/heureka/appProps.template.json
- apps/heureka/src/App.tsx
- apps/heureka/src/components/Issues/Issues.tsx
- apps/heureka/src/components/Services/Services.tsx
- apps/heureka/src/components/Shell/Shell.tsx
Adds `initialFilters.support_group` as the default filter in `Services` and maps `supportGroupCcrn` to `support_group` for consistency.
- Added initialFilters type
- Passed InitialFilters to Services and Issues
- Set as default filter in Services
1. `npm i`
2. `npx turbo dev --filter @cloudoperators/juno-app-heureka` --> add before the appProps
> feat(heureka): adds initialFilters support group as default filter in services

- apps/heureka/src/components/Services/Services.test.tsx
- apps/heureka/src/components/Services/ServicesList/ServicesList.test.tsx
- package-lock.json
This is to address the urgent issue where `test` step started failing _only_ on CI for no apparent reason and without this we'll not be able to merge any PR. An investigation [task](https://github.com/cloudoperators/juno/issues/838) has been added to the epic.
- #838 
1. `npm i`
2. `npm run test`
> test(heureka): skip tests that fail only on CI

- .changeset/healthy-needles-return.md
- packages/k8s-client/eslint.config.mjs
- packages/k8s-client/src/apiErrorHandler.ts
- packages/k8s-client/src/client.ts
- packages/k8s-client/src/request.ts
- packages/k8s-client/src/watch.ts
- packages/k8s-client/test/client.test.ts
- packages/k8s-client/test/request.test.ts
- Fix typescript errors (k8s client)
- Overhaul of JavaScript Client for Kubernetes Communication: https://github.com/cloudoperators/juno/issues/812
1. `npm i`
> refactor(juno): fix typescript errors (k8s client)

- .changeset/two-squids-brake.md
- apps/heureka/src/components/Services/useFetchServices.ts
- apps/heureka/src/generated/graphql.ts
Fixes the issue of missing current filters when using service pagination and clarifies code by setting default options directly in `useLazyQuery`, allowing customization within the query function. This eliminates one `useCallback`, making the code clearer and more concise.
- useFetchServices
1. `npm i`
2. `npx turbo dev --filter @cloudoperators/juno-app-heureka`
> fix(heureka): fixes the issue of missing current filters when using service pagination

- .changeset/angry-sloths-clean.md
- .changeset/fair-moose-check.md
- apps/heureka/src/components/Services/ServiceDetails/ServiceDetails.tsx
- apps/heureka/src/components/Services/ServicePanel/ServicePanel.test.tsx
- apps/heureka/src/components/Services/ServicePanel/ServicePanel.tsx
- apps/heureka/src/components/Services/ServicesList/ServicesList.tsx
- apps/heureka/src/components/Services/common/ImageVersionDetailsPanel/ImageVersionDetailsPanel.tsx
- apps/heureka/src/components/Services/common/ImageVersionDetailsPanel/index.ts
- apps/heureka/src/components/Services/common/ServiceImageVersions/ServiceImageVersions.tsx
- apps/heureka/src/components/Services/useFetchServiceImageVersions.ts
- apps/heureka/src/components/Services/utils.ts
- apps/heureka/src/components/common/Breadcrumb/Breadcrumb.tsx
- apps/heureka/src/generated/graphql.ts
- apps/heureka/src/graphql/Services/getServiceImageVersions.graphql
- apps/heureka/src/store/StoreProvider/stateReducer.ts
- apps/heureka/src/store/StoreProvider/types.ts
This PR adds a third section to the service details page, which displays detailed information about a selected image version. The image version can be selected in two ways:
Directly within the service details page from the image version table, which then reveals the third section with detailed information about the selected image version.
From the panel, where selecting an image version updates the service details page to display the detailed information of that image version, along with the first two sections—one containing service details and the other listing all related image versions for that service.
- Extended the ServiceDetails component to display detailed information about the selected image version.
- Updated store types and reducers to support selecting an image version action …
> feat(heureka): adds an image version details info to service details page

- .changeset/sweet-trees-design.md
- apps/heureka/src/components/Services/ServiceDetails/ServiceDetails.tsx
- apps/heureka/src/components/Services/ServicesList/ServicesList.tsx
- apps/heureka/src/components/Services/common/ServiceImageVersions/ServiceImageVersions.tsx
- apps/heureka/src/components/Services/common/ServiceImageVersions/ServiceImageVersionsItem.tsx
- apps/heureka/src/styles.scss
Generalizes classes to highlight lists on hover and applies the class to all lists.
- Added generic class to highlight datagrids
- Added the class to all existing lists
- Removed not necessary Stack components in ServiceDetails
- Removed also unnecessary classes `overflow-auto` and `w-full`
- Split ServiceImageVersions into two components to render independent the list items.
1. `npm i`
2. `npx turbo dev --filter @cloudoperators/juno-app-heureka`
> fix(heureka): adds hover to all lists

- apps/heureka/src/components/Services/ServiceDetails/ServiceDetails.tsx
- apps/heureka/src/components/Services/common/ImageVersionDetailsPanel/ImageVersionDetailsPanel.tsx
- apps/heureka/src/components/Services/common/ServiceImageVersions/ServiceImageVersions.tsx
- apps/heureka/src/components/Services/common/ServiceImageVersions/ServiceImageVersionsItem.tsx
- apps/heureka/src/components/Services/utils.ts
- apps/heureka/src/store/StoreProvider/types.ts
Cleaned up image version types by removing duplicates and unnecessary mappings that caused confusion. Now, only the essential types are created during fetching and reused throughout the application.
- Unified types
- Normalised ComponentInstance to own types because of simplicity
1. `npm i`
2. `npx turbo dev --filter @cloudoperators/juno-app-heureka`
> chore(heureka): cleanup imageversions types

- .changeset/silver-boxes-crash.md
- apps/heureka/src/components/Services/ServicePanel/ServicePanel.test.tsx
- apps/heureka/src/components/Services/ServicesList/ServiceListItem/ServiceListItem.tsx
- apps/heureka/src/components/Services/ServicesList/ServicesList.test.tsx
- apps/heureka/src/components/Services/ServicesList/ServicesList.tsx
- apps/heureka/src/components/Services/common/ImageVersionDetailsPanel/ImageVersionIssuesList.tsx
- apps/heureka/src/components/Services/common/ServiceImageVersions/ServiceImageVersions.tsx
- apps/heureka/src/components/Services/common/ServiceImageVersions/ServiceImageVersionsItem.tsx
- apps/heureka/src/components/common/IssuesCountBadges/IssuesCount.tsx
- apps/heureka/src/components/common/IssuesCountBadges/IssuesCountBadges.tsx
- apps/heureka/src/components/common/IssuesCountBadges/index.ts
The counts per severity are now displayed in separate columns with minimum widths to improve styling.
- IssueCount component is added to display a badge with a respective icon and color per severity
- Services list and list item are adjusted to use this component
- Image versions list and list item are adjusted to use this component
- Issue 1: [[link to issue](https://github.com/cloudoperators/juno/issues/622#issuecomment-2770697472)]
1. `npm i`
> chore(heureka): shows counts separate columns in lists

- apps/greenhouse/README.md
This update clarifies the authentication behavior when isMock is set. Specifically, it documents that isMock takes precedence over token-based authentication, regardless of whether a demoUserToken or demoOrg is provided. This ensures developers are aware that mock authentication will override other methods if enabled. The clarification has been added to improve transparency and prevent confusion for the dev setup for the backend.
- Greenhouse readme updated.
- https://github.com/cloudoperators/greenhouse/pull/1049
- https://github.com/cloudoperators/greenhouse/issues/1048
> chore(greenhouse): clarifies that isMock, when set, takes precedence over token-based authentication

- .changeset/gentle-walls-poke.md
- apps/greenhouse/src/components/Extensions.tsx
Propagates the authentication token as appProp to the extensions temporary so it can be used against the API.
- Extension loader injects the token as appProp so it can be used to authenticate against the API.
1. `npm i`
2. `npx turbo dev --filter @cloudoperators/juno-app-greenhouse`
> feat(greenhouse): propagates token to the Extensions

- .changeset/violet-parents-melt.md
- apps/heureka/src/components/ServiceDetails/index.tsx
This pull request improves the user experience on the Service Details page by ensuring that if an already selected image version is reselected, the corresponding details panel will now close automatically—matching the behavior on the Services List page.
- Updated the serviceDetails component to handle image version reselection.
- Issue 1: https://github.com/cloudoperators/juno/issues/887
1. `npm i`
> chore(heureka): closes image version details panel on reselect in Service Details page

- .changeset/giant-ghosts-yell.md
- packages/k8s-client/package.json
- packages/k8s-client/src/index.ts
- packages/k8s-client/vite.config.ts
This pull request (PR) introduces support for the CommonJS module format in our build process. This enhancement ensures better compatibility and interoperability with various JavaScript environments.
1. `npm i`
> chore(k8s): add cjs format to build

- .github/workflows/deploy-pr-preview.yaml
- apps/carbon/README.md
This PR fixes an issue where the PR preview workflow failed to post a comment with the preview link on the pull request.
Previously, the workflow ran without explicitly defined permissions (defaulting to full access). Due to recent security requirements (e.g. CodeQL), we now set explicit permissions. However, the pull-requests: write permission was missing, which prevented the workflow from commenting on the PR.
- Add write permissions to the PR Prview Workflow
- Same happened with hugo-documentation-templater: https://github.com/sapcc/hugo-documentation-templater/pull/46/files
> chore(ci): add pull-requests: write permission to PR preview workflow

- .github/renovate.json
Renovate was not running as expected, and no dependency update PRs were appearing. After investigating the issue, it was found that the Renovate configuration contained validation errors reported by the official validator tool:
```
INFO: Validating .github/renovate.json
ERROR: Found errors in configuration
"file": ".github/renovate.json",
"errors": [
{
"topic": "Configuration Error",
"message": "The following managers configured in enabledManagers are not supported: \"pnpm\""
},
{
"topic": "Configuration Error",
"message": "packageRules[1]: packageRules cannot combine both matchUpdateTypes and rangeStrategy. Rule: {\"groupName\":\"dependencies for ui-components\",\"matchDatasources\":[\"npm\"],\"matchFileNames\":[\"packages/ui-components/**\"],\"matchUpdateTypes\":[\"minor\",\"patch\"],\"m …
```
> chore(ci): fixes renovate configuration

- .changeset/rich-otters-agree.md
- apps/heureka/src/components/Services/ServicesList/ServicePanel.test.tsx
- apps/heureka/src/components/Services/ServicesList/index.test.tsx
- apps/heureka/src/components/Services/utils.ts
- apps/heureka/src/components/types.ts
- apps/heureka/src/graphql/Services/getServices.graphql
- apps/heureka/src/mocks/fixtures/services.ts
The `objectMetadata` fields are unused in the application and are leftover data that negatively impact API performance. Since they are expensive to compute and not displayed in the UI, we need to remove them.
- getServices query is updated to remove `objectMetadata`
No issue is created, reported by API colleagues.
1. `pnpm i`
2. `pnpm TASK`
> fix(heureka): removes unnecessary fields from getServices to improve performance

- .changeset/breezy-baths-switch.md
- .github/scripts/build-vite-app.sh
- .github/workflows/deploy-pr-preview.yaml
- apps/heureka/index.html
This PR addresses the issue where `appProps.json` fetch was not working from a child route like `/services/:name` when page is refreshed. 
- Load `appProps.json` from supplied `VITE_APP_PROPS_URL` or load it from server root `/appProps.json`.
- Updated github pr-preview for Heureka by supplying correct url to `appProps.json`.
1. `pnpm i`
2. `pnpm TASK`
> fix(heureka): allow changing appProps.json url

- .changeset/weak-vans-cough.md
- apps/heureka/src/components/Service/ImageVersionDetailsPanel/index.tsx
If there is no image version selected instead of displaying `Image version not found` render nothing.
- Remove unnecessary message
1. `pnpm i`
2. `pnpm TASK`
- [] I have commented my code, particularly in hard-to-understand areas.
> fix(heureka): remove no image version message

- apps/heureka/src/components/Services/Services.test.tsx
- apps/heureka/src/components/Services/ServicesList/ServicePanel.test.tsx
- apps/heureka/src/components/Services/ServicesList/index.test.tsx
- apps/heureka/src/components/common/Filters/FilterSelect.test.tsx
- apps/heureka/src/components/common/Filters/index.test.tsx
This PR fixes failing tests because of the timeout. 
The issue seems to be that the apis, like `getByRole`, `getByTestId`, `getByText` are synchronous and expect elements to be rendered without waiting for them to be rendered, therefore replacing them with the asynchronous counterparts like `findByText`, `findByTestId`, `findByRole` waits for the element to appear in the DOM (up to the default timeout), making it robust against async rendering.
- Used asynchronous `screen` APIs instead of the synchronous ones.
1. `pnpm i`
2. `pnpm TASK`
- [] I have added tests that prove my fix is effective or that my feature works.
> test(heureka): fix flaky tests

- .github/workflows/build-push-greenhouse-image.yaml
- .github/workflows/build-push-supernova-image.yaml
This PR improves the readability of vulnerability scan results by adding a second Trivy scan using the table output format. This human-friendly format makes it easier for developers to quickly analyze findings directly in the GitHub Actions logs.
- Added a second Trivy step that runs with format: table for clear, readable logs.
- Reuses cache from the prior Trivy scan to avoid redundant work.
- #984
> chore(ci): enhance Trivy Output Readability with Table Format (Dual Scan with Caching)

- .changeset/stale-towns-win.md
- apps/example/src/components/metrics/MetricsBox.tsx
- apps/example/src/components/peaks/list/CreatePeakModal.tsx
- packages/ui-components/src/components/Modal/Modal.component.tsx
- packages/ui-components/src/components/Modal/Modal.stories.tsx
- packages/ui-components/src/components/Modal/Modal.test.tsx
- packages/ui-components/src/components/ModalFooter/ModalFooter.component.tsx
- packages/ui-components/src/components/ModalFooter/ModalFooter.stories.tsx
- packages/ui-components/src/components/ModalFooter/ModalFooter.test.tsx
Issue: https://github.com/cloudoperators/juno/issues/1010
- Added `disableConfirmButton` and `disableCancelButton` props to `Modal` and `ModalFooter` so users can disable these in-built buttons during invalid input states or asynchronous operations.
- Fulfilled all ACs.
- This solution isn't applicable to Example App's current use cases. However, `MetricsBox` was updated to use `Modal`'s in-built confirmation props, instead of custom buttons.
- Logically grouped and ordered existing component props.
> feat(ui): disable in-built confirm and cancel buttons

- .changeset/thick-needles-accept.md
- .github/licenserc.yaml
- apps/heureka/codegen.ts
- apps/heureka/src/generated/graphql.ts
This PR updates types based on announced schema breaking changes to change severity filter type. This change should be shipped to Greenhouse qa asap, since the schema changes are available in heureka endpoint for greenhouse qa.
- graphql.ts is updated based on the latest schema change
- Autogenerated files (**/generated/** ) are now exlcuded from checking the license header
- Issue 1: https://github.com/cloudoperators/heureka/issues/787
1. `pnpm i`
2. `pnpm TASK`
> feat(heureka): updates types to resolve schema breaking change

- .changeset/neat-paths-leave.md
- apps/heureka/src/components/common/Filters/FilterSelect.test.tsx
This PR skips one test for FilterSelect component as it is not stable and timeout is happening often on this test. Currently we skip it untill it will be fixed properly. 
No issue is created for it.
1. `pnpm i`
2. `pnpm TASK`
> chore(heureka): skips filterSelect test temporary as it is not stable

- .changeset/odd-squids-slide.md
- apps/heureka/src/components/common/Filters/FilterSelect.test.tsx
- apps/heureka/src/components/common/Filters/index.test.tsx
Although we skipped some filter-related tests in Heureka, the PR test jobs still fail occasionally. Because of this, I have temporarily skipped all filter-related tests and will investigate further to fix them properly. Hopefully, the other tests won’t fail anymore.
- Filter and FilterSelect tests are skipped.
No issue is created.
1. `pnpm i`
2. `pnpm TASK`
> fix(heureka): skips all Filter related test temporarily as they fail

- .changeset/eighty-parks-think.md
- .changeset/free-lights-mate.md
- .changeset/new-houses-find.md
- .changeset/pretty-eagles-kiss.md
- apps/doop/src/components/violations/ViolationDetails.tsx
- apps/doop/src/components/violations/ViolationsListItem.tsx
- apps/greenhouse/src/components/nav/PluginNav.tsx
- apps/supernova/src/components/CustomAppShell.tsx
- apps/supernova/src/components/alerts/Alert.tsx
This PR addresses issue's that have been found by Esther while testing it on QA.
- `supernova` now remembers url state of a visited page and restores it back when the page is visited again. This fixes the issues of filters being removed when navigating to Alerts after coming from another page like `Silences` and vice versa.
- `greenhouse` now remembers url state of an application and restores it back when opened again.
- In `supernova`: Selected alert in the url state gets removed when clicking on the same item in the list.
- In `doop`:  Selected `violationGroup` gets added and removed to the url when panel opens or closes.
- https://github.com/cloudoperators/juno/issues/1173
1. `pnpm i`
2. `pnpm TASK`
Review the [PR Manifesto](https://github.com/cloudoperators/juno/blob/main/docs/pr_manif …
> fix(juno): address issues from url refactoring topic
